# Security Review Configuration

# Available Models:
# - claude-sonnet-4-20250514 (default) - Best for most PRs
# - claude-opus-4-1-20250805 - Maximum accuracy for critical code  
# - claude-3-5-sonnet-20241022 - Budget option
# - claude-3-haiku-20240307 - Quick scans

# Vulnerability categories to check
categories:
  - sql_injection
  - xss
  - command_injection
  - path_traversal
  - authentication_bypass
  - insecure_crypto
  - hardcoded_secrets
  - xxe_injection
  - deserialization
  - file_upload

# File patterns to review
include_patterns:
  - "*.php"
  - "*.js"
  - "*.ts"
  - "*.jsx"
  - "*.tsx"
  - "*.yml"
  - "*.yaml"
  - "*.sh"
  - "composer.json"
  - "package.json"

# File patterns to exclude from review
exclude_patterns:
  - "tests/**"
  - "vendor/**"
  - "node_modules/**"
  - "*.min.js"
  - "*.min.css"
  - "build/**"
  - "dist/**"
  - "*.md"

# Severity thresholds
severity_levels:
  block_on: HIGH        # Block PR merge on HIGH severity
  warn_on: MEDIUM      # Warn but don't block on MEDIUM
  info_on: LOW         # Information only for LOW

# Custom rules for this project
custom_rules:
  - name: "WordPress Nonce Check"
    pattern: "wp_verify_nonce"
    message: "Ensure nonces are properly verified for all form submissions"
    severity: MEDIUM
    
  - name: "WordPress Capability Check"
    pattern: "current_user_can"
    message: "Verify user capabilities before performing privileged actions"
    severity: HIGH
    
  - name: "Direct Database Access"
    pattern: "$wpdb->query"
    message: "Use prepared statements with $wpdb->prepare() for all database queries"
    severity: HIGH
    
  - name: "File Upload Validation"
    pattern: "wp_handle_upload"
    message: "Ensure file type and size validation for uploads"
    severity: MEDIUM
    
  - name: "API Key Storage"
    pattern: "CLAUDE_API_KEY|API_KEY|SECRET_KEY"
    message: "Never hardcode API keys. Use WordPress options or environment variables"
    severity: HIGH

# False positive suppression
suppressions:
  - file: "84em-local-pages.php"
    line: 325
    reason: "API key is encrypted before storage"
    
  - file: "tests/**"
    reason: "Test files excluded from security review"

# Notification settings
notifications:
  post_pr_comment: true
  require_approval_for_high: true
  auto_approve_if_clean: false
  
# Additional security checks
additional_checks:
  dependency_audit: true
  static_analysis: true
  pattern_matching: true