name: Deploy to Staging

on:
  pull_request:
    types: [closed]
    branches: [staging]
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force deployment (skip checks)'
        required: false
        default: false
        type: boolean
      skip_backup:
        description: 'Skip backup creation (use with caution)'
        required: false
        default: false
        type: boolean

jobs:
  deploy:
    name: Staging Deployment
    # Only run if the PR was merged (not just closed) OR manual trigger
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      environment: staging
      force_deploy: ${{ github.event.inputs.force_deploy || false }}
      skip_backup: ${{ github.event.inputs.skip_backup || false }}
    secrets:
      DEPLOY_HOST: ${{ secrets.STAGING_DEPLOY_HOST }}
      DEPLOY_USER: ${{ secrets.STAGING_DEPLOY_USER }}
      DEPLOY_PATH: ${{ secrets.STAGING_DEPLOY_PATH }}
      DEPLOY_SSH_KEY: ${{ secrets.STAGING_DEPLOY_SSH_KEY }}
      DEPLOY_PORT: ${{ secrets.STAGING_DEPLOY_PORT }}
      BACKUP_PATH: ${{ secrets.STAGING_BACKUP_PATH }}
      HEALTH_CHECK_URL: ${{ secrets.STAGING_HEALTH_CHECK_URL }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}