name: Security Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.php'
      - '**.js'
      - '**.ts'
      - '**.jsx'
      - '**.tsx'
      - '**.yml'
      - '**.yaml'
      - '**.sh'
      - 'composer.json'
      - 'package.json'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  security-review:
    name: Claude Security Review
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
        fetch-depth: 2
    
    - name: Run Claude Security Review
      uses: anthropics/claude-code-security-review@main
      with:
        claude-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
        comment-pr: true
        upload-results: true
        exclude-directories: 'vendor,node_modules,build,dist,tests'
        claudecode-timeout: 20
        run-every-commit: false

  # Optional: Run additional security tools
  dependency-check:
    name: Dependency Security Check
    runs-on: ubuntu-latest
    if: contains(fromJSON('["composer.json", "composer.lock", "package.json", "package-lock.json"]'), github.event.pull_request.changed_files)
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer:v2
        
    - name: Check PHP dependencies
      if: hashFiles('composer.lock') != ''
      run: |
        composer install --no-scripts --no-progress
        composer audit || true
        
    - name: Setup Node.js
      if: hashFiles('package-lock.json') != ''
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Check Node.js dependencies
      if: hashFiles('package-lock.json') != ''
      run: |
        npm ci
        npm audit --audit-level=high || true