name: Basic Checks

on:
  push:
    branches: [ main, dev, develop, 'feature/**' ]
  pull_request:
    branches: [ main, dev, develop ]

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    
    name: PHP Syntax Check
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, intl, openssl
    
    - name: Check PHP syntax
      run: |
        find . -name "*.php" -not -path "./vendor/*" -exec php -l {} \; | grep -v "No syntax errors"
        echo "✅ All PHP files have valid syntax"
    
    - name: Check composer.json validity
      run: |
        composer validate --no-check-all --no-check-publish
        echo "✅ composer.json is valid"

  # Note: Full WP-CLI tests are run locally
  # GitHub Actions environment has issues with WP-CLI command registration
  # Run tests locally with: wp 84em local-pages --test --all