name: Basic Checks

on:
  push:
    branches: [ main, dev, develop, 'feature/**' ]
  pull_request:
    branches: [ main, dev, develop ]

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    
    name: PHP Syntax Check
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, intl, openssl
        tools: composer:v2
    
    - name: Check PHP syntax
      run: |
        echo "Checking PHP syntax..."
        error_count=0
        while IFS= read -r -d '' file; do
          output=$(php -l "$file" 2>&1)
          if [[ $? -ne 0 ]] || [[ "$output" != *"No syntax errors"* ]]; then
            echo "❌ Syntax error in $file:"
            echo "$output"
            error_count=$((error_count + 1))
          fi
        done < <(find . -name "*.php" -not -path "./vendor/*" -print0)
        
        if [[ $error_count -gt 0 ]]; then
          echo "❌ Found $error_count file(s) with syntax errors"
          exit 1
        else
          echo "✅ All PHP files have valid syntax"
        fi
    
    - name: Cache Composer dependencies
      uses: actions/cache@v4
      with:
        path: vendor
        key: composer-${{ hashFiles('composer.lock') }}
        restore-keys: composer-
    
    - name: Install Composer dependencies
      run: |
        echo "Installing Composer dependencies..."
        composer install --no-dev --optimize-autoloader --no-progress
    
    - name: Check composer.json validity
      run: |
        composer validate --no-check-all --no-check-publish
        echo "✅ composer.json is valid"

  # Note: Full WP-CLI tests are run locally
  # GitHub Actions environment has issues with WP-CLI command registration
  # Run tests locally with: wp 84em local-pages --test --all